# Generated by Django 5.0.7 on 2024-07-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_x_start', models.IntegerField()),
                ('position_x_end', models.IntegerField()),
                ('position_y_start', models.IntegerField()),
                ('position_y_end', models.IntegerField()),
                ('categories', models.ManyToManyField(blank=True, to='maps.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.shop')),
            ],
        ),
    ]
